export const runtime:
  | undefined
  | 'edge-routine'
  | 'azion'
  | 'workerd'
  | 'deno'
  | 'lagon'
  | 'react-native'
  | 'moddable'
  | 'netlify'
  | 'electron'
  | 'node'
  | 'bun'
  | 'react-server'
  | 'edge-light'
  | 'fastly'
  | 'kiesel'
  | 'wasmer'
  | 'browser' = 'fastly'
export const environment: undefined | 'development' | 'production' | 'staging' = 'staging'
