export const runtime:
  | 'azion'
  | 'browser'
  | 'bun'
  | 'deno'
  | 'edge-light'
  | 'edge-routine'
  | 'electron'
  | 'fastly'
  | 'kiesel'
  | 'lagon'
  | 'moddable'
  | 'netlify'
  | 'node'
  | 'react-native'
  | 'react-server'
  | 'wasmer'
  | 'workerd'
  | undefined = 'workerd'
export const environment: 'development' | 'production' | 'staging' | undefined = undefined
